Implement color extension function for String
ziggy42/kolor pull request #13
Opened 2020-03-24 18:03 UTC by tonsV2

Assuming you accept this pull request I would suggest you take it one step further and use this color extension function to implement all the other extension functions.

`fun String.black() = this.color(BLACK)`

Another thing, one of the things which makes Kotlin beautiful is that it's less verbose than Java. Instead of System.out.println we simply write println. With that in mind I'll encourage importing "com.andreapivetta.kolor.Color.*" so all colors aren't prefixed with "Color.".

Thanks for a nice library.

2020-03-25 10:47 UTC, ziggy42 commented
Hey @tonsV2 , thanks for your contribution. I think it would make sense to use `fun String.black() = this.color(BLACK)`, you can go ahead and add it to this PR.

For your second point, I'll think about it a bit more.

2020-03-25 13:57 UTC, tonsV2 commented
Hi @ziggy42, I've updated my commit.

2020-03-31 21:01 UTC, ziggy42 requested changes

2020-03-31 21:01 UTC, ziggy42 commented on src/main/kotlin/com/andreapivetta/kolor/Extensions.kt
> +fun String.backgroundColor(color: Color) = Kolor.background(this, color)
Please add a `\n`

2022-03-09 07:51 UTC, closed without merging